import {
  BOARD_SIZE,
  cloneBoard,
  forwardDirection,
  isPromotionRow,
  onBoard,
  pieceAt,
  setPiece,
} from "./board";
import type { Board, Color, GameState, Move, Piece, Square } from "./types";

const DIRECTIONS: ReadonlyArray<readonly [number, number]> = [
  [-1, -1],
  [-1, 1],
  [1, -1],
  [1, 1],
];

interface Continuation {
  readonly jumped: Square;
  readonly landing: Square;
}

function keyOf(s: Square): string {
  return `${s.row},${s.col}`;
}

/**
 * Generate every legal move for the player to move.
 *
 * Russian rules: if any capture exists, only captures are legal.
 * Among captures, the player may choose any sequence (we return them all).
 */
export function getLegalMoves(state: GameState): Move[] {
  const captures = generateAllCaptures(state.board, state.turn);
  if (captures.length > 0) return captures;
  return generateSimpleMoves(state.board, state.turn);
}

/**
 * Returns true if the player to move has any legal capture available.
 * Useful for UI hints (capture must be made).
 */
export function hasMandatoryCapture(state: GameState): boolean {
  return generateAllCaptures(state.board, state.turn).length > 0;
}

/**
 * All capture sequences for every piece of the given color.
 */
function generateAllCaptures(board: Board, color: Color): Move[] {
  const out: Move[] = [];
  for (let row = 0; row < BOARD_SIZE; row++) {
    for (let col = 0; col < BOARD_SIZE; col++) {
      const p = board[row][col];
      if (!p || p.color !== color) continue;
      generateCapturesForPiece(board, { row, col }, out);
    }
  }
  return out;
}

/**
 * Push every maximal capture sequence starting from `start` into `out`.
 *
 * The chain is generated by depth-first search over continuations from each
 * landing square. Turkish-strike rules apply: captured pieces remain on the
 * board until the chain ends, so they block paths and cannot be jumped twice.
 * Promotion mid-chain upgrades the piece to a king for subsequent jumps.
 */
function generateCapturesForPiece(
  board: Board,
  start: Square,
  out: Move[]
): void {
  const piece = pieceAt(board, start);
  if (!piece) return;

  // Working board: piece removed from its start square (it's "in flight").
  // Captured pieces are NOT removed; they stay as frozen obstacles tracked via
  // capturedKeys until the chain terminates.
  const initialWB = cloneBoard(board);
  setPiece(initialWB, start, null);

  const recurse = (
    wb: (Piece | null)[][],
    current: Square,
    currentPiece: Piece,
    captured: Square[],
    path: Square[],
    capturedKeys: Set<string>
  ): void => {
    const conts = findImmediateCaptures(wb, current, currentPiece, capturedKeys);

    if (conts.length === 0) {
      if (captured.length > 0) {
        out.push({
          from: start,
          to: current,
          path: [...path],
          captures: [...captured],
          promoted: !piece.king && currentPiece.king,
        });
      }
      return;
    }

    for (const cont of conts) {
      const nextWB = wb.map((r) => [...r]);
      setPiece(nextWB, current, null);
      const becomesKing =
        !currentPiece.king &&
        isPromotionRow(cont.landing.row, currentPiece.color);
      const nextPiece: Piece = {
        color: currentPiece.color,
        king: currentPiece.king || becomesKing,
      };
      setPiece(nextWB, cont.landing, nextPiece);

      const nextKeys = new Set(capturedKeys);
      nextKeys.add(keyOf(cont.jumped));

      recurse(
        nextWB,
        cont.landing,
        nextPiece,
        [...captured, cont.jumped],
        [...path, cont.landing],
        nextKeys
      );
    }
  };

  recurse(initialWB, start, piece, [], [], new Set());
}

/**
 * Find one-jump continuations from `current` for `piece`.
 *
 * Men: jump exactly one diagonal step over an enemy to an empty square beyond.
 * Kings: fly along a diagonal — find the first non-frozen enemy in each
 * direction, then any empty square beyond it (before the next obstacle) is a
 * valid landing. capturedKeys treats already-captured pieces as opaque blockers.
 */
function findImmediateCaptures(
  wb: ReadonlyArray<ReadonlyArray<Piece | null>>,
  from: Square,
  piece: Piece,
  capturedKeys: ReadonlySet<string>
): Continuation[] {
  const out: Continuation[] = [];

  for (const [dr, dc] of DIRECTIONS) {
    if (piece.king) {
      let r = from.row + dr;
      let c = from.col + dc;
      let enemyAt: Square | null = null;

      while (onBoard(r, c)) {
        const cell = wb[r][c];
        const frozen = capturedKeys.has(`${r},${c}`);

        if (cell === null) {
          if (enemyAt) {
            out.push({ jumped: enemyAt, landing: { row: r, col: c } });
          }
        } else if (frozen) {
          break; // already-captured piece blocks further scan
        } else if (cell.color === piece.color) {
          break; // friend blocks
        } else {
          // unjumped enemy
          if (enemyAt) break; // can't jump over two in a row
          enemyAt = { row: r, col: c };
        }

        r += dr;
        c += dc;
      }
    } else {
      const er = from.row + dr;
      const ec = from.col + dc;
      const lr = from.row + 2 * dr;
      const lc = from.col + 2 * dc;

      if (!onBoard(lr, lc)) continue;
      const enemy = wb[er][ec];
      if (!enemy || enemy.color === piece.color) continue;
      if (capturedKeys.has(`${er},${ec}`)) continue;
      if (wb[lr][lc] !== null) continue;

      out.push({
        jumped: { row: er, col: ec },
        landing: { row: lr, col: lc },
      });
    }
  }

  return out;
}

/**
 * Non-capturing moves for the given color. Men: 1 step forward diagonally.
 * Kings: any number of empty squares along a diagonal.
 */
function generateSimpleMoves(board: Board, color: Color): Move[] {
  const out: Move[] = [];

  for (let row = 0; row < BOARD_SIZE; row++) {
    for (let col = 0; col < BOARD_SIZE; col++) {
      const piece = board[row][col];
      if (!piece || piece.color !== color) continue;
      const from: Square = { row, col };

      if (piece.king) {
        for (const [dr, dc] of DIRECTIONS) {
          let r = row + dr;
          let c = col + dc;
          while (onBoard(r, c) && board[r][c] === null) {
            const to: Square = { row: r, col: c };
            out.push({
              from,
              to,
              path: [to],
              captures: [],
              promoted: false,
            });
            r += dr;
            c += dc;
          }
        }
      } else {
        const fwd = forwardDirection(color);
        for (const dc of [-1, 1] as const) {
          const r = row + fwd;
          const c = col + dc;
          if (!onBoard(r, c)) continue;
          if (board[r][c] !== null) continue;
          const to: Square = { row: r, col: c };
          out.push({
            from,
            to,
            path: [to],
            captures: [],
            promoted: isPromotionRow(r, color),
          });
        }
      }
    }
  }

  return out;
}

/**
 * Find the legal Move (if any) matching a from→to attempt by the user.
 * Useful for click-to-move UI when only the destination square is known.
 *
 * If multiple capture sequences start from `from` and end at `to`, returns
 * the FIRST match in generation order — UI should normally disambiguate
 * by surfacing the list and asking the user.
 */
export function findMoveByEndpoints(
  state: GameState,
  from: Square,
  to: Square
): Move | null {
  const moves = getLegalMoves(state);
  return (
    moves.find(
      (m) =>
        m.from.row === from.row &&
        m.from.col === from.col &&
        m.to.row === to.row &&
        m.to.col === to.col
    ) ?? null
  );
}

/**
 * All legal moves that begin at the given square.
 * Used by Board UI to highlight possible destinations once a piece is selected.
 */
export function legalMovesFromSquare(
  state: GameState,
  from: Square
): Move[] {
  return getLegalMoves(state).filter(
    (m) => m.from.row === from.row && m.from.col === from.col
  );
}
